"""
Final book compilation to .docx and .txt.

Logic:
1. Check final_review_notes_status gate
2. Fetch all chapters in order
3. Compile into .docx (with formatting) and .txt
4. Upload to Supabase Storage
5. Set book_output_status = 'compiled'
"""

import os
from docx import Document
from docx.shared import Pt, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
import db
import notifications


def run_compile_stage(book_id: str) -> dict:
    """
    Compile all chapters into a final .docx and .txt book file.

    Returns a dict with:
      - status: "completed", "paused_waiting_final_notes", "error"
      - docx_path: path to the generated .docx file
      - txt_path: path to the generated .txt file
      - message: human-readable status
    """
    print(f"\n{'='*60}")
    print(f"  📚 FINAL COMPILATION STAGE — Book: {book_id}")
    print(f"{'='*60}")

    # Fetch book
    book = db.get_book(book_id)
    if not book:
        return {"status": "error", "message": f"Book not found: {book_id}"}

    title = book["title"]
    final_status = book.get("final_review_notes_status", "no")
    final_notes = book.get("final_review_notes")

    # GATE: Check final_review_notes_status
    if final_status == "no_notes_needed":
        print(f"  ✅ final_review_notes_status = 'no_notes_needed' → Proceeding.")
    elif final_status == "yes" and final_notes:
        print(f"  ✅ Final review notes provided. Proceeding with notes.")
    elif final_status == "yes" and not final_notes:
        msg = (
            f"final_review_notes_status = 'yes' but no notes found.\n"
            f"Add 'final_review_notes' in the books table, then re-run."
        )
        notifications.notify(book_id, "compile_paused", msg)
        return {
            "status": "paused_waiting_final_notes",
            "message": msg,
        }
    else:
        msg = (
            f"final_review_notes_status = '{final_status}' → Pausing.\n"
            f"Set to 'no_notes_needed' to compile, or 'yes' to add final notes."
        )
        notifications.notify(book_id, "compile_paused", msg)
        return {
            "status": "paused_no_status",
            "message": msg,
        }

    # Fetch all chapters
    chapters = db.get_chapters(book_id)
    if not chapters:
        return {"status": "error", "message": "No chapters found. Run chapter stage first."}

    # Sort by chapter_number
    chapters = sorted(chapters, key=lambda c: c["chapter_number"])
    print(f"  Found {len(chapters)} chapters to compile.")

    # Create output directory
    output_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "output")
    os.makedirs(output_dir, exist_ok=True)

    # Clean filename
    safe_title = "".join(c for c in title if c.isalnum() or c in " -_").strip()
    safe_title = safe_title.replace(" ", "_")

    # Generate .docx
    docx_path = os.path.join(output_dir, f"{safe_title}.docx")
    _generate_docx(title, chapters, docx_path, final_notes)
    print(f"  ✅ DOCX created: {docx_path}")

    # Generate .txt
    txt_path = os.path.join(output_dir, f"{safe_title}.txt")
    _generate_txt(title, chapters, txt_path)
    print(f"  ✅ TXT created: {txt_path}")

    # Upload to Supabase Storage
    try:
        _upload_to_storage(book_id, docx_path, safe_title)
        print(f"  ✅ Uploaded to Supabase Storage.")
    except Exception as e:
        print(f"  [WARNING] Failed to upload to storage: {e}")

    # Update book status
    db.update_book(book_id, {"book_output_status": "compiled"})

    # Notify
    msg = (
        f"📚 Book '{title}' has been compiled!\n"
        f"DOCX: {docx_path}\n"
        f"TXT: {txt_path}\n"
        f"Chapters: {len(chapters)}"
    )
    notifications.notify(book_id, "book_compiled", msg)

    return {
        "status": "completed",
        "docx_path": docx_path,
        "txt_path": txt_path,
        "message": msg,
    }


def _generate_docx(title: str, chapters: list[dict], filepath: str, final_notes: str | None = None) -> None:
    """Generate a formatted .docx file from chapters."""
    doc = Document()

    # Title Page
    # Add some spacing before title
    for _ in range(6):
        doc.add_paragraph("")

    title_para = doc.add_paragraph()
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = title_para.add_run(title)
    run.bold = True
    run.font.size = Pt(28)

    # Subtitle
    subtitle = doc.add_paragraph()
    subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = subtitle.add_run("Generated by Automated Book Generation System")
    run.font.size = Pt(12)
    run.italic = True

    # Page break after title
    doc.add_page_break()

    # Table of Contents
    toc_heading = doc.add_heading("Table of Contents", level=1)
    for ch in chapters:
        toc_entry = doc.add_paragraph(
            f"Chapter {ch['chapter_number']}: {ch['title']}",
            style="List Number"
        )

    doc.add_page_break()

    # Chapters
    for ch in chapters:
        # Chapter heading
        doc.add_heading(f"Chapter {ch['chapter_number']}: {ch['title']}", level=1)

        # Chapter content — split by paragraphs
        content = ch.get("content", "")
        for paragraph_text in content.split("\n"):
            paragraph_text = paragraph_text.strip()
            if not paragraph_text:
                continue

            # Detect sub-headings (lines starting with ## or bold markers)
            if paragraph_text.startswith("##"):
                clean = paragraph_text.lstrip("#").strip()
                doc.add_heading(clean, level=2)
            elif paragraph_text.startswith("**") and paragraph_text.endswith("**"):
                clean = paragraph_text.strip("*").strip()
                doc.add_heading(clean, level=2)
            else:
                doc.add_paragraph(paragraph_text)

        # Page break between chapters
        doc.add_page_break()

    # Final Notes (if any)
    if final_notes:
        doc.add_heading("Editor's Final Notes", level=1)
        doc.add_paragraph(final_notes)

    doc.save(filepath)


def _generate_txt(title: str, chapters: list[dict], filepath: str) -> None:
    """Generate a plain .txt file from chapters."""
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(f"{'='*60}\n")
        f.write(f"{title.center(60)}\n")
        f.write(f"{'='*60}\n")
        f.write(f"Generated by Automated Book Generation System\n")
        f.write(f"{'='*60}\n\n")

        # Table of Contents
        f.write("TABLE OF CONTENTS\n")
        f.write("-" * 40 + "\n")
        for ch in chapters:
            f.write(f"  Chapter {ch['chapter_number']}: {ch['title']}\n")
        f.write("\n" + "=" * 60 + "\n\n")

        # Chapters
        for ch in chapters:
            f.write(f"\n{'─'*60}\n")
            f.write(f"CHAPTER {ch['chapter_number']}: {ch['title'].upper()}\n")
            f.write(f"{'─'*60}\n\n")
            f.write(ch.get("content", "") + "\n")

        f.write(f"\n{'='*60}\n")
        f.write("END OF BOOK\n")
        f.write(f"{'='*60}\n")


def _upload_to_storage(book_id: str, filepath: str, safe_title: str) -> None:
    """Upload the compiled file to Supabase Storage."""
    client = db.get_client()
    filename = os.path.basename(filepath)
    storage_path = f"{book_id}/{filename}"

    with open(filepath, "rb") as f:
        file_data = f.read()

    # Upload to book-outputs bucket
    client.storage.from_("book-outputs").upload(
        path=storage_path,
        file=file_data,
        file_options={"content-type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document"}
    )