-- Create all tables

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- BOOKS table
CREATE TABLE IF NOT EXISTS books (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    title                   TEXT NOT NULL,
    notes_on_outline_before TEXT,                         -- Required before generating outline
    outline                 TEXT,                         -- Generated by LLM
    notes_on_outline_after  TEXT,                         -- Optional post-outline notes
    status_outline_notes    TEXT DEFAULT 'no',            -- yes / no / no_notes_needed
    final_review_notes_status TEXT DEFAULT 'no',          -- yes / no / no_notes_needed
    final_review_notes      TEXT,                         -- Notes for final draft revision
    book_output_status      TEXT DEFAULT 'pending',       -- pending / outline_done / chapters_done / compiled / paused
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW()
);

-- CHAPTERS table
CREATE TABLE IF NOT EXISTS chapters (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    book_id                 UUID NOT NULL REFERENCES books(id) ON DELETE CASCADE,
    chapter_number          INTEGER NOT NULL,
    title                   TEXT,                         -- Chapter title from outline
    content                 TEXT,                         -- Full chapter text
    summary                 TEXT,                         -- LLM-generated summary for context chaining
    chapter_notes           TEXT,                         -- Editor notes for this chapter
    chapter_notes_status    TEXT DEFAULT 'no_notes_needed', -- yes / no / no_notes_needed
    status                  TEXT DEFAULT 'pending',       -- pending / generated / approved
    created_at              TIMESTAMPTZ DEFAULT NOW(),
    updated_at              TIMESTAMPTZ DEFAULT NOW()
);

-- NOTIFICATION LOGS table
CREATE TABLE IF NOT EXISTS notification_logs (
    id                      UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    book_id                 UUID REFERENCES books(id) ON DELETE SET NULL,
    event_type              TEXT NOT NULL,                -- e.g. outline_ready, chapter_waiting, etc.
    message                 TEXT NOT NULL,                -- Notification content
    channel                 TEXT,                         -- email / teams / console
    sent_at                 TIMESTAMPTZ DEFAULT NOW()
);

-- INDEXES for performance
CREATE INDEX IF NOT EXISTS idx_chapters_book_id ON chapters(book_id);
CREATE INDEX IF NOT EXISTS idx_chapters_order ON chapters(book_id, chapter_number);
CREATE INDEX IF NOT EXISTS idx_notification_logs_book_id ON notification_logs(book_id);

-- AUTO-UPDATE updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE TRIGGER set_books_updated_at
    BEFORE UPDATE ON books
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE OR REPLACE TRIGGER set_chapters_updated_at
    BEFORE UPDATE ON chapters
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- STORAGE BUCKET (Supabase-specific, run in Supabase SQL Editor)
INSERT INTO storage.buckets (id, name, public)
VALUES ('book-outputs', 'book-outputs', true)
ON CONFLICT (id) DO NOTHING;